Repository creativecolab/d4sd-portal, pull requests merged in 2019-11, with the labels that each got.

#41 Replacing with d4sd components
  package-lock.json
  package.json
  src/components/login-card/index.tsx
  src/components/login-card/style.less
  src/components/signup-card/index.tsx
  src/components/signup-card/style.less
Labels: Issue: New Feature, PR: Good to Merge

#45 Typography
  public/index.html
  src/components/login-card/index.tsx
  src/components/login-card/style.less
  src/components/signup-card/index.tsx
  src/index.css
Labels: Issue: New Feature, PR: Good to Merge

#46 Menubar
  .eslintrc.js
  config-overrides.js
  src/assets/daniel.png
  src/assets/logo-blue.svg
  src/assets/logo.svg
  src/components/menubar/index.tsx
  src/components/menubar/style.less
  src/index.tsx
  src/styles/vars.less
  yarn.lock
Labels: Issue: New Feature, PR: Good to Merge, Priority: Medium

#51 Code of ethics component
  .gitignore
  src/components/ethics-card/index.tsx
  src/components/ethics-card/style.less
  src/index.tsx
Labels: Issue: New Feature, PR: Good to Merge

#47 Redux Boilerplate (Closes #54)
  package-lock.json
  package.json
  src/actions/types.ts
  src/components/signup-card/index.tsx
  src/containers/forms/signin-form.tsx
  src/containers/signin-page.tsx
  src/index.tsx
  src/logo.svg
  src/reducers/index.ts
  src/serviceWorker.ts
  src/store.ts
  tsconfig.json
Labels: Issue: Dependencies, Issue: New Feature, PR: Good to Merge

#44 Sign Up Page Layout
  package-lock.json
  package.json
  public/index.html
  src/components/layouts/signup-layout/index.tsx
  src/components/layouts/signup-layout/style.less
  src/components/login-card/style.less
  src/components/menubar/index.tsx
  src/components/menubar/style.less
  src/components/signup-card/index.tsx
  src/components/signup-card/style.less
  src/index.css
  src/index.tsx
  src/styles/fonts.css
  src/styles/fonts.less
  src/styles/vars.less
Labels: Issue: New Feature, PR: Needs Review

#60 Made the role card, removed hard coded styling.
  package-lock.json
  package.json
  src/components/ethics-card/index.tsx
  src/components/ethics-card/style.less
  src/components/layouts/signup-layout/index.tsx
  src/components/layouts/signup-layout/style.less
  src/components/role-card/index.tsx
  src/components/role-card/style.less
  src/components/signup-card/index.tsx
  src/index.tsx
  src/styles/fonts.less
  src/styles/vars.less
Labels: Issue: New Feature, PR: Needs Review

#50 Signup participant feedback component
  src/components/signup-choice/index.tsx
  src/components/signup-choice/style.less
  src/index.tsx
Labels: Issue: New Feature, PR: Good to Merge, PR: Merge Conflict

#65 Added Routing with SignupPage
  src/components/menubar/index.tsx
  src/components/signup-card/index.tsx
  src/containers/signin-page.tsx
  src/containers/signup-page.tsx
  src/index.tsx
Labels: Issue: New Feature, PR: Needs Review, Priority: Medium

#67 Adding ESlint + Prettier to DevOps
  .eslintrc.js
  .vscode/settings.json
  config-overrides.js
  custom.d.ts
  package-lock.json
  package.json
  public/index.html
  src/actions/types.ts
  src/components/ethics-card/index.tsx
  src/components/ethics-card/style.less
  src/components/layouts/signup-layout/index.tsx
  src/components/layouts/signup-layout/style.less
  src/components/login-card/index.tsx
  src/components/login-card/style.less
  src/components/menubar/index.tsx
  src/components/menubar/style.less
  src/components/signup-card/index.tsx
  src/components/signup-card/style.less
  src/containers/forms/signin-form.tsx
  src/index.css
  src/index.tsx
  src/react-app-env.d.ts
  src/reducers/index.ts
  src/store.ts
  src/styles/fonts.less
  src/styles/mixins.less
  src/styles/reset.css
  src/styles/vars.less
  tsconfig.json
Labels: Issue: DevOps, PR: Merge Conflict, PR: Reviewed w/Comments, Priority: Medium

#69 Card remodelling
  package-lock.json
  package.json
  src/components/ethics-card/index.tsx
  src/components/ethics-card/style.less
  src/components/layouts/signup-layout/index.tsx
  src/components/layouts/signup-layout/style.less
  src/components/login-card/style.less
  src/components/role-card/index.tsx
  src/components/role-card/style.less
  src/components/signup-card/index.tsx
  src/components/signup-card/style.less
  src/styles/fonts.less
  src/styles/vars.less
Labels: Issue: New Feature, PR: Needs Review, Priority: Medium

#74 Move reset.css behind
  src/index.less
  src/index.tsx
  src/styles/fonts.less
Labels: Issue: Bug, PR: Good to Merge

#80 Fixes Netlify Routing
  netlify.toml
  public/_redirects
Labels: Issue: Bug, PR: Needs Review

#75 Reformat Code to Fit ESlint Settings
  package-lock.json
  src/components/ethics-card/index.tsx
  src/components/layouts/signup-layout/index.tsx
  src/components/signup-card/index.tsx
Labels: Issue: Dependencies, PR: Good to Merge

#81 Removed Parenthesis from Master
  src/components/layouts/signup-layout/index.tsx
  src/components/role-card/index.tsx
  src/components/signup-choice/index.tsx
  src/containers/signup-page.tsx
Labels: Issue: Fix, PR: Needs Review

#72 Login card and layout, also seperate signup and login with router
  src/components/layouts/login-layout/index.tsx
  src/components/layouts/login-layout/style.less
  src/components/layouts/signup-layout/index.tsx
  src/components/login-card/index.tsx
  src/components/login-card/style.less
  src/containers/login-page.tsx
  src/index.tsx
Labels: Issue: New Feature, PR: Needs Review

#70 Menubar handling logged in and off and logo/profile pic bug fix
  src/components/menubar/index.tsx
  src/components/menubar/style.less
Labels: Issue: Bug, PR: Needs Review

#83 Added Favicon to Portal
  public/favicon.ico
Labels: Issue: New Feature, PR: Needs Review, Priority: High

#84 Email flow (signup -> close tab -> continue from email -> login -> ...)
  .gitignore
  package-lock.json
  package.json
  src/actions/firebase.ts
  src/components/layouts/signup-layout/index.tsx
  src/components/layouts/workspace-layout/index.tsx
  src/components/layouts/workspace-layout/style.less
  src/components/signup-card/index.tsx
  src/containers/login-page.tsx
  src/index.tsx
  src/styles/vars.less
Labels: Issue: New Feature, Priority: Medium

#86 Fix href prop on Sign Up Button
  src/components/signup-card/index.tsx
Labels: Issue: Bug, PR: Needs Review, Priority: High
