Repository creativecolab/d4sd-portal, pull requests merged in 2020-01, with the labels that each got.

#93 Preliminary submission
  .eslintrc.js
  .vscode/settings.json
  package-lock.json
  package.json
  src/assets/img/style.less
  src/components/layouts/preliminary-submission-layout/index.tsx
  src/components/layouts/preliminary-submission-layout/style.less
  src/components/menubar/index.tsx
  src/components/preliminarysubmission-cards/feedback/index.tsx
  src/components/preliminarysubmission-cards/feedback/style.less
  src/components/preliminarysubmission-cards/how-it-works/index.tsx
  src/components/preliminarysubmission-cards/how-it-works/style.less
  src/components/preliminarysubmission-cards/prelim-finish/index.tsx
  src/components/preliminarysubmission-cards/prelim-finish/style.less
  src/components/preliminarysubmission-cards/project-info/index.tsx
  src/components/preliminarysubmission-cards/project-info/style.less
  src/components/preliminarysubmission-cards/upload/index.tsx
  src/components/preliminarysubmission-cards/upload/style.less
  src/index.tsx
  src/store.ts
  src/styles/fonts.less
  src/types/index.d.ts
Labels: PR: Needs Review

#114 Fix Logo in Mobile View
  src/components/menubar/index.tsx
  src/components/menubar/style.less
Labels: PR: Good to Merge

#95 Workspace action cards
  src/assets/content.js
  src/components/layouts/workspace-layout/index.tsx
  src/components/layouts/workspace-layout/style.less
Labels: PR: Good to Merge, PR: Needs Review

#128 Fix Typo on Challenges Page
  src/components/layouts/challenge-layout/index.tsx
Labels: Issue: Bug, PR: Good to Merge
