Repository creativecolab/d4sd-portal, pull requests merged in 2020-02, with the labels that each got.

#131 View Feedback Page
  public/index.html
  src/components/layouts/view-feedback-layout/index.tsx
  src/components/layouts/view-feedback-layout/style.less
  src/index.tsx
Labels: PR: Merge Conflict

#126 Workspace action cards (lint)
  package.json
  src/assets/content.ts
  src/components/layouts/workspace-layout/index.tsx
  src/components/layouts/workspace-layout/style.less
Labels: PR: Good to Merge

#139 Fix css load ordering
  package-lock.json
  package.json
  src/index.less
  src/index.tsx
Labels: PR: Good to Merge

#141 Arrow svg for workspace cards
  package-lock.json
  package.json
Labels: PR: Good to Merge

#136 Summit Card + SVG Swap
  package-lock.json
  src/assets/content.ts
  src/assets/img/d4sd_horizontal.svg
  src/assets/img/d4sd_triangle.svg
  src/assets/img/home_landing.svg
  src/assets/img/summit_1.jpg
  src/assets/img/summit_2.jpg
  src/assets/img/summit_3.jpg
  src/assets/img/summit_4.jpg
  src/assets/img/summit_bg.svg
  src/assets/img/summit_pics.png
  src/components/layouts/feedback-provider-layout/index.tsx
  src/components/layouts/feedback-provider-layout/provider-information.tsx
  src/components/layouts/feedback-provider-layout/question-list.tsx
  src/components/layouts/feedback-provider-layout/solution-view.tsx
  src/components/layouts/feedback-provider-layout/submission-preview.tsx
  src/components/layouts/home-layout/index.tsx
  src/components/layouts/home-layout/style.less
  src/components/layouts/view-feedback-layout/index.tsx
  src/components/preliminarysubmission-cards/prelim-finish/index.tsx
  src/index.tsx
  src/pages/About.js
  src/pages/Home.js
Labels: Production

#146 Get Rid of Home Nav + Fix Summit Card CSS
  src/components/layouts/home-layout/style.less
  src/components/menubar/index.tsx
Labels: Issue: Bug, Issue: New Feature, PR: Good to Merge

#129 Submission to Firebase write
  config/prod/.env.production
  config/staging/.env.production
  package-lock.json
  package.json
  src/actions/firebase.ts
  src/actions/useFirebaseUpload.ts
  src/components/Header/index.tsx
  src/components/layouts/home-layout/index.tsx
  src/components/layouts/login-layout/index.tsx
  src/components/layouts/preliminary-submission-layout/index.tsx
  src/components/layouts/signup-layout/index.tsx
  src/components/login-card/index.tsx
  src/components/menubar/index.tsx
  src/components/preliminarysubmission-cards/feedback/index.tsx
  src/components/preliminarysubmission-cards/feedback/style.less
  src/components/preliminarysubmission-cards/prelim-finish/index.tsx
  src/components/preliminarysubmission-cards/project-info/index.tsx
  src/components/preliminarysubmission-cards/upload/index.tsx
  src/components/signup-card/index.tsx
  src/contexts/SubmissionContext.tsx
  src/index.tsx
Labels: PR: Merge Conflict

#149 Sl/hotfix home
  src/assets/content.ts
  src/components/ScrollToTop.js
  src/components/ScrollToTop.tsx
  src/components/layouts/attend-layout/index.tsx
  src/components/layouts/attend-layout/style.less
  src/components/layouts/home-layout/index.tsx
  src/components/layouts/home-layout/style.less
  src/components/menubar/index.tsx
  src/index.tsx
  src/styles/containers.less
Labels: Issue: New Feature, Production

#150 Attend Page
  src/assets/content.ts
  src/assets/img/attend_header.svg
  src/components/Header/style.less
  src/components/layouts/attend-layout/index.tsx
  src/components/layouts/attend-layout/style.less
  src/components/layouts/workspace-layout/index.tsx
  src/components/menubar/index.tsx
  src/containers/attend-page.tsx
  src/index.tsx
Labels: Issue: New Feature, PR: Merge Conflict, Production

#151 Home Hotfixes
  package.json
  src/assets/content.ts
  src/assets/img/involve_partner.svg
  src/assets/img/workspace_header.svg
  src/components/Header/index.tsx
  src/components/layouts/attend-layout/index.tsx
  src/components/layouts/attend-layout/style.less
  src/components/layouts/home-layout/index.tsx
  src/components/layouts/home-layout/style.less
  src/components/layouts/sponsors-layout/index.tsx
  src/components/layouts/workspace-layout/index.tsx
  src/components/menubar/index.tsx
Labels: PR: Merge Conflict, Production

#155 Summit Banner (Home Page)
  src/assets/content.ts
  src/components/layouts/home-layout/index.tsx
  src/components/layouts/home-layout/style.less
Labels: Issue: New Feature, PR: Needs Review, Priority: High, Production
